version: '3.8'

services:


  mongodb-dev:
    image: mongo:4.4.4
    restart: unless-stopped
    env_file:
      - ./.env
    ports:
      - $MONGODB_LOCAL_PORT:$MONGODB_DOCKER_PORT
    environment:
      - MONGO_INITDB_ROOT_USERNAME=$MONGODB_USER
      - MONGO_INITDB_ROOT_PASSWORD=$MONGODB_PASS
    volumes:
      - ./db-dump:/db-dump
      - ./data:/data/db

  rebbl:
    depends_on:
      - mongodb-dev
    env_file: ./.env
    working_dir: /usr/src/rebbl
    build:
      context: ./
      dockerfile: ./docker/Dockerfile-node
    expose:
      - 3000
    environment:
      - NODE_ENV=development
      - DB_HOST=mongodb-dev
      - DB_NAME=$MONGODB_DATABASE
      - DB_PORT=$MONGODB_DOCKER_PORT
      - DB_USER=$MONGODB_USER
      - DB_PASS=$MONGODB_PASS
      - redditKey=$redditKey
      - redditSecret=$redditSecret
      - rebblPlannerKey=$rebblPlannerKey
      - rebblPlannerSecret=$rebblPlannerSecret
      - redditUsername=$redditUsername
      - redditPassword=$redditPassword
      - cyanideKey=$cyanideKey
      - cyanideApiHost=$cyanideApiHost
      - clientId=$clientId
      - clientSecret=$clientSecret
      - tennantId=$tennantId
      - scope=$scope
      - apiUrl=$apiUrl
      - verifyToken=$verifyToken
      - rampuphook=$rampuphook
      - errorhook=$errorhook
      - oiwebhook=$oiwebhook
      - redditcallbackURL=$redditcallbackURL
      - mongoDBUri=$mongoDBUri
      - imperiumKey=$imperiumKey
      - storage=$storage
      - discordClientId=$discordClientId
      - discordClientSecret=$discordClientSecret
      - discordCallbackURL=$discordCallbackURL
      - discordSignupCallbackURL=$discordSignupCallbackURL


